### ISSUE TITLE
3D print team marker and paint it.

### ISSUE THREAD

**Issue by gitikagorthi** [FTC-9073-Knightrix/2018-19-Knightrix#11]

**Comment by gitikagorthi** [comment]
We need painters tape to 3D print the team marker (which is already designed).

**Comment by gitikagorthi** [comment]
Mr. Bravo needs to 3D print the team marker.

**Comment by ibravo** [comment]
@gitikagorthi Can you please add the team marker files to this ticket?

**Comment by ibravo** [comment]
I've purchased new paints and reprinted the base in Knightrix purple. Please use Thursday meeting to continue printing the marker.
