### ISSUE TITLE
Parts to buy

### ISSUE THREAD

**Issue by nicolasbravo** [FTC-9073-Knightrix/2018-19-Knightrix#20]

**Comment by ibravo** [comment]
@vraj123 , can you please add to this ticket the list of parts that you looked for the Intake during last meeting? I couldn't find it in any of the CAD tickets.

**Comment by ibravo** [comment]
Ok, found the parts list in the Dropbox file. Here they are. We will also need to buy a motor.

Parts to Buy:
https://www.servocity.com/rev-core-hex-motor-mount
http://www.andymark.com/product-p/am-2915.htm
http://www.revrobotics.com/rev-41-1300/
http://www.revrobotics.com/rev-41-1146/ 
http://www.revrobotics.com/rev-41-1348/
http://www.revrobotics.com/rev-41-1327/

**Comment by ronbaer** [comment]
all parts on order
