### ISSUE TITLE
ARNAV NEEDS TO OPEN UP THE DRIVETRAIN BOX AND BUILD IT 

### ISSUE THREAD

**Issue by vjay49** [FTC-9073-Knightrix/2018-19-Knightrix#9]
Wait for the gear. Two more weeks :(

**Comment by teenymermaid** [comment]
who is vijay

**Comment by teenymermaid** [comment]
vijay u finish the intake

**Comment by teenymermaid** [comment]
vijay u cant build

**Comment by teenymermaid** [comment]
http://files.andymark.com/AssemblyInstructions/am-3437_HDmec+TileRunner+HDMecanum+User+Guide.pdf

**Comment by skinariwala** [comment]
Need pieces. Location in the engineering meeting entry.

**Comment by ibravo** [comment]
@vraj123 Can you please add the pieces that we need to buy to this ticket so Mr Baer can complete the purchase? 
Thanks

**Comment by vraj123** [comment]
Parts needed:  16 Pico  Spacer  (am-3406)(http://www.andymark.com/product-p/am-3406.htm)  and 8 63mm Churro (am-3399) (https://www.andymark.com/product-p/am-churro.htm)

**Comment by ibravo** [comment]
Instructions on the Drive Train purchased:
http://files.andymark.com/AssemblyInstructions/am-3437_HDmec+TileRunner+HDMecanum+User+Guide.pdf
